// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Verce11o/effective-mobile-test/internal/domain"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Verce11o/effective-mobile-test/internal/models"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateCars provides a mock function with given fields: ctx, cars
func (_m *Repository) CreateCars(ctx context.Context, cars []domain.Car) error {
	ret := _m.Called(ctx, cars)

	if len(ret) == 0 {
		panic("no return value specified for CreateCars")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Car) error); ok {
		r0 = rf(ctx, cars)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCar provides a mock function with given fields: ctx, carID
func (_m *Repository) DeleteCar(ctx context.Context, carID int) error {
	ret := _m.Called(ctx, carID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, carID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCars provides a mock function with given fields: ctx, input
func (_m *Repository) GetCars(ctx context.Context, input domain.GetCarsRequest) (models.CarList, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetCars")
	}

	var r0 models.CarList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetCarsRequest) (models.CarList, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetCarsRequest) models.CarList); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CarList)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetCarsRequest) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCar provides a mock function with given fields: ctx, carID, input
func (_m *Repository) UpdateCar(ctx context.Context, carID int, input domain.UpdateCarsRequest) error {
	ret := _m.Called(ctx, carID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.UpdateCarsRequest) error); ok {
		r0 = rf(ctx, carID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
